{% set name = "openff-nagl-models" %}
{% set version = "2025.9.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 136628907cadb4e374b5696c24dca78ec31cd228e8e72ed77ab602329590c2d0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioningit
    - setuptools
  run:
    - python >={{ python_min }}
    - platformdirs
    - importlib_resources
    - packaging
  run_constrained:
    - openff-nagl >=0.4.0

test:
  imports:
    - openff.nagl_models
  requires:
    - pip
    - python {{ python_min }} 

about:
  home: https://github.com/openforcefield/openff-nagl-models
  summary: 'NAGL models released by the Open Force Field Initiative'
  description: |
    This package contains NAGL models released by the Open Force Field Initiative.
    They are intended to be used by OpenFF NAGL.
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://github.com/openforcefield/openff-nagl-models
  dev_url: https://github.com/openforcefield/openff-nagl-models

extra:
  recipe-maintainers:
    - lilyminium
    - mattwthompson
    - j-wags
